<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" StylesheetTheme="themes" Title="Teddy book"%>


 <asp:Content ID="maincontent" ContentPlaceHolderID="Updatebooks" runat="server">
 <p class="editbooks">Update books (staff only).</p>

 <script language="C#" runat="server">
     
    void refreshGridUpdate(object sender, DetailsViewUpdatedEventArgs e)
    {
        gvbutternut2.DataBind();
    }

    void refreshGridDelete(object sender, DetailsViewDeletedEventArgs e)
    {
        gvbutternut2.DataBind();
        gvbutternut2.SelectedIndex = -1;
    }
    void refreshGridAddnewbook(object sender, EventArgs e)
    {
        Response.Redirect("~/locked/addbook.aspx");
        
    }
</script>

 <asp:AccessDataSource ID="butternut2DS" runat="server" 
    DataFile="~/butternut2.mdb"
    SelectCommand="SELECT * FROM [books]">
</asp:AccessDataSource>

<asp:AccessDataSource ID="butternut2DS2" runat="server" DataFile="~/butternut2.mdb"
    SelectCommand="SELECT * FROM [books] WHERE ID = ?" 
    UpdateCommand="UPDATE [books] SET ISBN = ?, APN = ?, book_title = ?, book_author = ?, book_description = ?, book_price = ?, 
    number_pages = ?, book_dimensions = ?, book_cover = ?, cover_image = ?, release_date = ?, Feature = ? WHERE ID = ?"
    DeleteCommand="DELETE FROM [books] WHERE ID = ?">


    <SelectParameters>
        <asp:ControlParameter ControlID="gvbutternut2" Name="ID" PropertyName="SelectedValue" Type="Int32" />
    </SelectParameters>

    <UpdateParameters>
            <asp:Parameter Name="ISBN" Type="String" />
            <asp:Parameter Name="APN" Type="String" />
            <asp:Parameter Name="book_title" Type="String" />
            <asp:Parameter Name="book_author" Type="String" />
            <asp:Parameter Name="book_description" Type="String" /> 
            <asp:Parameter Name="book_price" Type="double" />
            <asp:Parameter Name="number_pages" Type="Int32" />
            <asp:Parameter Name="book_dimensions" Type="String" />
            <asp:Parameter Name="book_cover" Type="String" />
            <asp:Parameter Name="cover_image" Type="String" />
            <asp:Parameter Name="release_date" Type="String" />
            <asp:Parameter Name="Feature" Type="Boolean" />
            <asp:Parameter Name="ID" Type="Int32" />
    </UpdateParameters>

    <DeleteParameters>
        <asp:Parameter Name="ID" Type="Int32" />
    </DeleteParameters>

</asp:AccessDataSource>

  <asp:DetailsView ID="dtlAmendbooks" DataKeyNames="ID" runat="server" AutoGenerateRows="false" EditRowStyle-BackColor="BlanchedAlmond" 
        DataSourceID="butternut2DS2" AutoGenerateEditButton="true" AutoGenerateDeleteBUtton="true" OnItemDeleted="refreshGridDelete"
        OnItemUpdated="refreshGridUpdate" Font-Names="Arial" Font-Size="12pt">

        <Fields>

            <asp:BoundField DataField="ID" visible = "false" />
          
          <asp:TemplateField HeaderText="ISBN">
          <EditItemTemplate>
            <asp:TextBox ID="isbnTextBox" runat="server" Text='<%# Bind("ISBN") %>' width="220" skinID ="textBox" />
          </EditItemTemplate>
          
          <ItemTemplate>
            <%# Eval("ISBN") %>
          </ItemTemplate>
        </asp:TemplateField>
        
        <asp:TemplateField HeaderText="APN">
          <EditItemTemplate>
            <asp:TextBox ID="apnTextBox" runat="server" Text='<%# Bind("APN") %>' width="220" skinID ="textBox" />
          </EditItemTemplate>
          
          <ItemTemplate>
            <%# Eval("APN") %>
          </ItemTemplate>
          
        </asp:TemplateField>

        <asp:TemplateField HeaderText="Title">
          <EditItemTemplate>
            <asp:TextBox ID="bookTitleTextBox" runat="server" Text='<%# Bind("book_title") %>' width="450" skinID ="textBox" />
          </EditItemTemplate>
          
          <ItemTemplate>
            <%# Eval("book_title") %>
          </ItemTemplate>
        </asp:TemplateField>

        <asp:TemplateField HeaderText="Author">
          <EditItemTemplate>
            <asp:TextBox ID="authorTextBox" runat="server" Text='<%# Bind("book_author") %>' width="220" skinID ="textBox" />
          </EditItemTemplate>
          
          <ItemTemplate> 
            <%# Eval("book_author") %>
          </ItemTemplate>
        </asp:TemplateField>

        <asp:TemplateField HeaderText="Description">
          <EditItemTemplate>
            <asp:TextBox ID="descriptionTextBox" runat="server" Mode="Multiline" Rows = "3" Text='<%# Bind("book_description") %>' 
            width="450" Height="100" TextMode="MultiLine" SkinID ="textBox" />
          </EditItemTemplate>
          
          <ItemTemplate>
            <%# Eval("book_description")%>
          </ItemTemplate>
        </asp:TemplateField>
        
        <asp:TemplateField HeaderText="Price">
          <EditItemTemplate>
            <asp:TextBox ID="priceTextBox" runat="server" Text='<%# Bind("book_price") %>' width="220" skinID ="textBox" />
          </EditItemTemplate>
          
          <ItemTemplate>
            <%# Eval("book_price")%>
          </ItemTemplate>
        </asp:TemplateField>
        
        <asp:TemplateField HeaderText="No.Pages">
          <EditItemTemplate>
            <asp:TextBox ID="pageTextBox" runat="server" Text='<%# Bind("number_pages") %>' width="220" skinID ="textBox" />
          </EditItemTemplate>
          
          <ItemTemplate>
            <%# Eval("number_pages")%>
          </ItemTemplate>
        </asp:TemplateField>
        
        <asp:TemplateField HeaderText="Size">
          <EditItemTemplate>
            <asp:TextBox ID="dimensionTextBox" runat="server" Text='<%# Bind("book_dimensions") %>' width="220" skinID ="textBox" />
          </EditItemTemplate>
          
          <ItemTemplate>
            <%# Eval("book_dimensions")%>
          </ItemTemplate>
        </asp:TemplateField>
        
        <asp:TemplateField HeaderText="Cover">
          <EditItemTemplate>
            <asp:TextBox ID="coverTextBox" runat="server" Text='<%# Bind("book_cover") %>' width="220" skinID ="textBox" />
          </EditItemTemplate>
          
          <ItemTemplate>
            <%# Eval("book_cover")%>
          </ItemTemplate>
        </asp:TemplateField>
        
        <asp:TemplateField HeaderText="Cover Pic.">
          <EditItemTemplate>
            <asp:TextBox ID="coverPicTextBox" runat="server" Text='<%# Bind("cover_image") %>' width="270" skinID ="textBox"/>
          </EditItemTemplate>
          
          <ItemTemplate>
            <img src = "<%# Eval("cover_image") %>" />
          </ItemTemplate>
        </asp:TemplateField>
        
        <asp:TemplateField HeaderText="Release Date">
          <EditItemTemplate>
            <asp:TextBox ID="releaseDateTextBox" runat="server" Text='<%# Bind("release_date") %>' width="220" skinID ="textBox" />
          </EditItemTemplate>
          
          <ItemTemplate>
            <%# Eval("release_date")%>
          </ItemTemplate>
        </asp:TemplateField>
        
        <asp:TemplateField HeaderText="Feature">
          <EditItemTemplate>
            <asp:CheckBox ID="featureTextBox" runat="server" Checked='<%# Bind("feature") %>' />
          </EditItemTemplate>
          
          <ItemTemplate>
            <%# Eval("Feature")%>
          </ItemTemplate>
        </asp:TemplateField>
                
        </Fields>
    </asp:DetailsView>
    <br />
    &nbsp;

    <asp:Button ID="addnewbook" runat="server" Text="Add New Book" OnClick="refreshGridAddnewbook" />
    <p></p>
    <asp:GridView id="gvbutternut2" runat="server" DataKeynames="ID" DataSourceID="butternut2DS" HeaderStyle-BackColor="CornflowerBlue" 
        HeaderStyle-ForeColor="White" CellPadding="3" Font-Names="arial" Font-Size="12pt" AutoGenerateColumns="false" 
        AllowPaging="true" PageSize="20" AllowSorting="true">
        
        <Columns>
            <asp:CommandField SelectText="Select" ShowSelectButton="true" />
            <asp:BoundField DataField="ISBN" HeaderText="ISBN" SortExpression="ISBN" />
            <asp:BoundField DataField="book_title" HeaderText="Title" SortExpression="book_title" />
            <asp:BoundField DataField="book_author" HeaderText="Auther" SortExpression="book_author" />
        </Columns>
        
    </asp:GridView>

 </asp:Content>